language: cpp

sudo: false

dist: trusty

# Handle git submodules yourself
git:
  submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i '' 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

compiler:
  - g++
  - clang

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lcov

branches:
  only:
  - master

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j4
  - ./bin/ceedukotests
  - ./bin/ceeduko ../boards/4x4_empty.board
  - ./bin/ceeduko ../boards/4x4_partial.board
  - ./bin/ceeduko ../boards/9x9_empty.board
  - ./bin/ceeduko ../boards/9x9_partial.board
  - ./bin/ceeduko ../boards/9x9_unsolvable.board
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build_coverage
  - cd build_coverage
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make -j4
  - ./bin/ceedukotests
  - ./bin/ceeduko ../boards/4x4_empty.board
  - ./bin/ceeduko ../boards/4x4_partial.board
  - ./bin/ceeduko ../boards/9x9_empty.board
  - ./bin/ceeduko ../boards/9x9_partial.board
  - ./bin/ceeduko ../boards/9x9_unsolvable.board

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build_debug
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
